-- MySQL Script generated by MySQL Workbench
-- 08/25/15 11:10:46
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`tipo_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tipo_usuario` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nombre` VARCHAR(45) NULL COMMENT '',
  `descripcion` VARCHAR(256) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `username` VARCHAR(45) NULL COMMENT '',
  `password` VARCHAR(45) NULL COMMENT '',
  `session` VARCHAR(45) NULL COMMENT '',
  `tipo_usuario_id` INT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_users_tipo_usuario` (`tipo_usuario_id` ASC)  COMMENT '',
  CONSTRAINT `fk_users_tipo_usuario`
    FOREIGN KEY (`tipo_usuario_id`)
    REFERENCES `mydb`.`tipo_usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tipo_stand`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tipo_stand` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nombre` VARCHAR(45) NULL COMMENT '',
  `permisos` INT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`puesto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`puesto` (
  `id` INT NOT NULL COMMENT '',
  `coordenadaX` INT NULL COMMENT '',
  `coordenadaY` INT NULL COMMENT '',
  `ancho` INT NULL COMMENT '',
  `largo` INT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`stand`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`stand` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `tipo_stand_id` INT NOT NULL COMMENT '',
  `nombre` VARCHAR(45) NOT NULL COMMENT '',
  `puesto_id` INT NULL COMMENT '',
  `imagen_base` VARCHAR(256) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_stand_tipo_stand1` (`tipo_stand_id` ASC)  COMMENT '',
  INDEX `fk_stand_puesto1` (`puesto_id` ASC)  COMMENT '',
  CONSTRAINT `fk_stand_tipo_stand1`
    FOREIGN KEY (`tipo_stand_id`)
    REFERENCES `mydb`.`tipo_stand` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_stand_puesto1`
    FOREIGN KEY (`puesto_id`)
    REFERENCES `mydb`.`puesto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`estado` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nombre` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ciudad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ciudad` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nombre` VARCHAR(45) NOT NULL COMMENT '',
  `estado_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_ciudad_estado1_idx` (`estado_id` ASC)  COMMENT '',
  CONSTRAINT `fk_ciudad_estado1`
    FOREIGN KEY (`estado_id`)
    REFERENCES `mydb`.`estado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`datos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`datos` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `users_id` INT NULL COMMENT '',
  `facebook` VARCHAR(125) NULL COMMENT '',
  `google` VARCHAR(125) NULL COMMENT '',
  `instagram` VARCHAR(45) NULL COMMENT '',
  `nombres` VARCHAR(45) NULL COMMENT '',
  `apellidos` VARCHAR(45) NULL COMMENT '',
  `fecha_nacimiento` DATE NULL COMMENT '',
  `genero` INT NULL COMMENT '',
  `telefono` VARCHAR(45) NULL COMMENT '',
  `cuidad` VARCHAR(45) NULL COMMENT '',
  `ciudad_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_datos_users1` (`users_id` ASC)  COMMENT '',
  INDEX `fk_datos_ciudad1_idx` (`ciudad_id` ASC)  COMMENT '',
  CONSTRAINT `fk_datos_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_datos_ciudad1`
    FOREIGN KEY (`ciudad_id`)
    REFERENCES `mydb`.`ciudad` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`datos_stand`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`datos_stand` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `logoyaccesomapa` VARCHAR(45) NULL COMMENT '',
  `stand24mts` VARCHAR(45) NULL COMMENT '',
  `stand48mts` VARCHAR(45) NULL COMMENT '',
  `usuariochat1` VARCHAR(45) NULL COMMENT '',
  `usuariochat2` VARCHAR(45) NULL COMMENT '',
  `pendon1` VARCHAR(45) NULL COMMENT '',
  `pendon2` VARCHAR(45) NULL COMMENT '',
  `pendon3` VARCHAR(45) NULL COMMENT '',
  `pendon4` VARCHAR(45) NULL COMMENT '',
  `pendon5` VARCHAR(45) NULL COMMENT '',
  `video1` VARCHAR(45) NULL COMMENT '',
  `video2` VARCHAR(45) NULL COMMENT '',
  `video3` VARCHAR(45) NULL COMMENT '',
  `informarcion` VARCHAR(45) NULL COMMENT '',
  `fondomural` VARCHAR(45) NULL COMMENT '',
  `galeriafotos` VARCHAR(45) NULL COMMENT '',
  `redessociales` VARCHAR(45) NULL COMMENT '',
  `stand_id` INT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_datos_stand_stand1` (`stand_id` ASC)  COMMENT '',
  CONSTRAINT `fk_datos_stand_stand1`
    FOREIGN KEY (`stand_id`)
    REFERENCES `mydb`.`stand` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`interesados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`interesados` (
  `idi` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `users_id` INT NULL COMMENT '',
  `stand_id` INT NULL COMMENT '',
  PRIMARY KEY (`idi`)  COMMENT '',
  INDEX `fk_interesados_users1` (`users_id` ASC)  COMMENT '',
  INDEX `fk_interesados_stand1` (`stand_id` ASC)  COMMENT '',
  CONSTRAINT `fk_interesados_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_interesados_stand1`
    FOREIGN KEY (`stand_id`)
    REFERENCES `mydb`.`stand` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tipo_institucion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tipo_institucion` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nombre` VARCHAR(45) NULL COMMENT '',
  `descripcion` VARCHAR(126) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`institucion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`institucion` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nombre` VARCHAR(45) NULL COMMENT '',
  `direccion` VARCHAR(45) NULL COMMENT '',
  `telefono` VARCHAR(45) NULL COMMENT '',
  `email` VARCHAR(45) NULL COMMENT '',
  `descripcion` VARCHAR(45) NULL COMMENT '',
  `lgoo` VARCHAR(45) NULL COMMENT '',
  `users_id` INT NULL COMMENT '',
  `tipo_institucion_id` INT NULL COMMENT '',
  `razon_social` VARCHAR(126) NULL COMMENT '',
  `RIF` VARCHAR(45) NULL COMMENT '',
  `website` VARCHAR(45) NULL COMMENT '',
  `facebook` VARCHAR(45) NULL COMMENT '',
  `twitter` VARCHAR(45) NULL COMMENT '',
  `instagram` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_institucion_users1` (`users_id` ASC)  COMMENT '',
  INDEX `fk_institucion_tipo_institucion1` (`tipo_institucion_id` ASC)  COMMENT '',
  CONSTRAINT `fk_institucion_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_institucion_tipo_institucion1`
    FOREIGN KEY (`tipo_institucion_id`)
    REFERENCES `mydb`.`tipo_institucion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`carrera`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`carrera` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `carrera` VARCHAR(45) NULL COMMENT '',
  `descripcion` VARCHAR(125) NULL COMMENT '',
  `institucion_id` INT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_carrera_institucion1` (`institucion_id` ASC)  COMMENT '',
  CONSTRAINT `fk_carrera_institucion1`
    FOREIGN KEY (`institucion_id`)
    REFERENCES `mydb`.`institucion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`categoria` (
  `id` INT NOT NULL COMMENT '',
  `nombre` VARCHAR(45) NULL COMMENT '',
  `descripcion` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`categoria_institucion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`categoria_institucion` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `categoria_id` INT NULL COMMENT '',
  `institucion_id` INT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_categoria_institucion_categoria1` (`categoria_id` ASC)  COMMENT '',
  INDEX `fk_categoria_institucion_institucion1` (`institucion_id` ASC)  COMMENT '',
  CONSTRAINT `fk_categoria_institucion_categoria1`
    FOREIGN KEY (`categoria_id`)
    REFERENCES `mydb`.`categoria` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_categoria_institucion_institucion1`
    FOREIGN KEY (`institucion_id`)
    REFERENCES `mydb`.`institucion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`responsable`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`responsable` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nombre` VARCHAR(125) NULL COMMENT '',
  `apellido` VARCHAR(125) NULL COMMENT '',
  `correo1` VARCHAR(45) NULL COMMENT '',
  `correo2` VARCHAR(45) NULL COMMENT '',
  `telefono1` VARCHAR(45) NULL COMMENT '',
  `telefono2` VARCHAR(45) NULL COMMENT '',
  `institucion_id` INT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_responsable_institucion1` (`institucion_id` ASC)  COMMENT '',
  CONSTRAINT `fk_responsable_institucion1`
    FOREIGN KEY (`institucion_id`)
    REFERENCES `mydb`.`institucion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`intereses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`intereses` (
  `id` INT NOT NULL COMMENT '',
  `nombres` VARCHAR(45) NULL COMMENT '',
  `descripcion` VARCHAR(126) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`intereses_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`intereses_users` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `intereses_id` INT NULL COMMENT '',
  `users_id` INT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_intereses_users_intereses1` (`intereses_id` ASC)  COMMENT '',
  INDEX `fk_intereses_users_users1` (`users_id` ASC)  COMMENT '',
  CONSTRAINT `fk_intereses_users_intereses1`
    FOREIGN KEY (`intereses_id`)
    REFERENCES `mydb`.`intereses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_intereses_users_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`color`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`color` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nombre` VARCHAR(45) NULL COMMENT '',
  `codigo` VARCHAR(45) NULL COMMENT '',
  `rgb` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`avatar_alto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`avatar_alto` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nombre` VARCHAR(45) NULL COMMENT '',
  `descripcion` VARCHAR(126) NULL COMMENT '',
  `color_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_avatar_alto_color1_idx` (`color_id` ASC)  COMMENT '',
  CONSTRAINT `fk_avatar_alto_color1`
    FOREIGN KEY (`color_id`)
    REFERENCES `mydb`.`color` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`avatar_medio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`avatar_medio` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nombre` VARCHAR(45) NULL COMMENT '',
  `descripcion` VARCHAR(126) NULL COMMENT '',
  `color_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_avatar_medio_color1_idx` (`color_id` ASC)  COMMENT '',
  CONSTRAINT `fk_avatar_medio_color1`
    FOREIGN KEY (`color_id`)
    REFERENCES `mydb`.`color` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`avatar_bajo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`avatar_bajo` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nombre` VARCHAR(45) NULL COMMENT '',
  `descripcion` VARCHAR(126) NULL COMMENT '',
  `color_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_avatar_bajo_color1_idx` (`color_id` ASC)  COMMENT '',
  CONSTRAINT `fk_avatar_bajo_color1`
    FOREIGN KEY (`color_id`)
    REFERENCES `mydb`.`color` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`avatar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`avatar` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nombre` VARCHAR(45) NULL COMMENT '',
  `descripcion` VARCHAR(126) NULL COMMENT '',
  `users_id` INT NULL COMMENT '',
  `avatar_alto_id` INT NULL COMMENT '',
  `avatar_medio_id` INT NULL COMMENT '',
  `avatar_bajo_id` INT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_avatar_users1` (`users_id` ASC)  COMMENT '',
  INDEX `fk_avatar_avatar_alto1` (`avatar_alto_id` ASC)  COMMENT '',
  INDEX `fk_avatar_avatar_medio1` (`avatar_medio_id` ASC)  COMMENT '',
  INDEX `fk_avatar_avatar_bajo1` (`avatar_bajo_id` ASC)  COMMENT '',
  CONSTRAINT `fk_avatar_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_avatar_avatar_alto1`
    FOREIGN KEY (`avatar_alto_id`)
    REFERENCES `mydb`.`avatar_alto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_avatar_avatar_medio1`
    FOREIGN KEY (`avatar_medio_id`)
    REFERENCES `mydb`.`avatar_medio` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_avatar_avatar_bajo1`
    FOREIGN KEY (`avatar_bajo_id`)
    REFERENCES `mydb`.`avatar_bajo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`avatar_stand`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`avatar_stand` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `avatar_id` INT NOT NULL COMMENT '',
  `stand_id` INT NOT NULL COMMENT '',
  `fecha` DATETIME NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_avatar_stand_avatar1_idx` (`avatar_id` ASC)  COMMENT '',
  INDEX `fk_avatar_stand_stand1_idx` (`stand_id` ASC)  COMMENT '',
  CONSTRAINT `fk_avatar_stand_avatar1`
    FOREIGN KEY (`avatar_id`)
    REFERENCES `mydb`.`avatar` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_avatar_stand_stand1`
    FOREIGN KEY (`stand_id`)
    REFERENCES `mydb`.`stand` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`imagen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`imagen` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `coorX` INT NULL COMMENT '',
  `coorY` INT NULL COMMENT '',
  `ancho` INT NULL COMMENT '',
  `alto` INT NULL COMMENT '',
  `link` VARCHAR(45) NULL COMMENT '',
  `stand_id` INT NOT NULL COMMENT '',
  `posicion` INT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_imagen_stand1_idx` (`stand_id` ASC)  COMMENT '',
  CONSTRAINT `fk_imagen_stand1`
    FOREIGN KEY (`stand_id`)
    REFERENCES `mydb`.`stand` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
